/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev3;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean searchInteger(ArrayList<Integer> array, int e) { 
        System.out.println("inside search"); 
        if (array == null) return false; 
        for (int elt : array) { 
            if (elt == e) return true; 
        } 
        return false; 
    }

    public static boolean searchString(ArrayList<String> array, String e) { 
        System.out.println("inside search"); 
        if (array == null) return false; 
        for (String elt : array) { 
            if (elt.equalsIgnoreCase(e)) return true; 
        } 
        return false; 
    }

    public static boolean deleteChar(ArrayList<Character> array, char e) { 
        System.out.println("inside search"); 
        if (array == null) return false; 
        if(array.remove(Character.valueOf(e))) return true;
        return false; 
    }
}
